<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::query()->updateOrCreate(
            ['email' => 'admin@iorder.test'],
            [
                'name' => 'iOrder Admin',
                'password' => Hash::make('password123'),
                'role' => 'admin',
            ],
        );

        User::query()->updateOrCreate(
            ['email' => 'staff@iorder.test'],
            [
                'name' => 'iOrder Staff',
                'password' => Hash::make('password123'),
                'role' => 'staff',
            ],
        );

        User::query()->updateOrCreate(
            ['email' => 'customer@iorder.test'],
            [
                'name' => 'iOrder Customer',
                'password' => Hash::make('password123'),
                'role' => 'customer',
            ],
        );

        Product::query()->upsert([
            [
                'name' => 'Republic Cement',
                'price' => 208,
                'stock_quantity' => 80,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liso Greeen 4x8',
                'price' => 400,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RSB 10mm',
                'price' => 125,
                'stock_quantity' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RSB 9mm 1.9 (Green)',
                'price' => 72.20,
                'stock_quantity' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GI Pipe S40 1 - 1/4',
                'price' => 865,
                'stock_quantity' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GI Pipe S40 1 - 1/2',
                'price' => 1,001,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GI Pipe S40 1 - 1/4',
                'price' => 865,
                'stock_quantity' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '7Star Corrogated Sheet(Green) 12ft',
                'price' => 372,
                'stock_quantity' => 40,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tabular 2x2(Blue) 2.0',
                'price' => 500,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tabular 2x3(Blue) 2.0',
                'price' => 650,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GI Steel Matting 3.5',
                'price' => 250,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GI Steel Matting 4.5',
                'price' => 500,
                'stock_quantity' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Flat Bar 3/8x2 - 1/2',
                'price' => 700,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Round Bar 8mm',
                'price' => 83,
                'stock_quantity' => 50,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tabular 3/4x3/4(Red) 1.5',
                'price' => 150,
                'stock_quantity' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GI Pipe S40 3/4',
                'price' => 402,
                'stock_quantity' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Square Bar(Red)',
                'price' => 210,
                'stock_quantity' => 20,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Channel Bar 2x5x5mm',
                'price' => 2,350,
                'stock_quantity' => 18,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'C Purlins 2x3(Green)',
                'price' => 260,
                'stock_quantity' => 40,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tabular 1x1x1.5(Red)',
                'price' => 185,
                'stock_quantity' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hardiflex 3.5',
                'price' => 305,
                'stock_quantity' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ball Valve(Greate Volume) 3/4',
                'price' => 500,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Welcoat Flatwall Enamel(Litro) White',
                'price' => 175,
                'stock_quantity' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Welcoat QDE White(Litro)',
                'price' => 187,
                'stock_quantity' => 24,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Welcoat QDE Crystal Green(Litro)',
                'price' => 500,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boysen Flat Latex White(Gallon)',
                'price' => 614.25,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tabular 2x2(Blue) 2.0',
                'price' => 500,
                'stock_quantity' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rain or Shine 701 E/P(Baguio Green) 16 - LT',
                'price' => 2,573,
                'stock_quantity' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rain or Shine 629 E/P Tulips 16 - LT',
                'price' => 2,573,
                'stock_quantity' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rain or Shine 701 E/P(Baguio Green) 4 - LT',
                'price' => 646,
                'stock_quantity' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Acrytex Primer 4 - LT',
                'price' => 943,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Acrytex Reducer 4 - LT',
                'price' => 454,
                'stock_quantity' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Acrylic Emulsion 1 - LT',
                'price' => 153,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Acrytex Primer 4 - LT',
                'price' => 943,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sand Paper 3M #1000',
                'price' => 13.25,
                'stock_quantity' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sand Paper 3M #120',
                'price' => 13.25,
                'stock_quantity' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sand Paper 3M #80',
                'price' => 13.25,
                'stock_quantity' => 100,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AIMEE Nylon Rope 5mm',
                'price' => 461,
                'stock_quantity' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AIMEE Nylon Rope 10mm',
                'price' => 1,669,
                'stock_quantity' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'China Smooth NAil 7/8',
                'price' => 83,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'China Smooth NAil 3/4',
                'price' => 88,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'High Performance Silicon Sealant ',
                'price' => 122,
                'stock_quantity' => 25,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guilder Proxy Primer Gray 4lts',
                'price' => 789,
                'stock_quantity' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bonsy Spray Paint (Black) 39',
                'price' => 83,
                'stock_quantity' => 36,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pioneer Elasto Seal Pisil Pack',
                'price' => 140,
                'stock_quantity' => 30,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['name'], ['price', 'stock_quantity', 'is_active', 'updated_at']);
    }
}
